- name: add weechat repo key
  become: true
  apt_key: >-
    keyserver=ha.pool.sks-keyservers.net
    id=11E9DE8848F2B65222AA75B8D1820DB22A11534E
- name: add weechat repo
  become: true
  apt_repository:
    repo: >-
      deb https://weechat.org/{{ansible_distribution|lower}}
      {{ansible_distribution_release}} main
    state: present
- name: install weechat
  become: true
  apt: package=weechat-curses state=latest
