- name: installing config plugin
  copy:
    src: files/ansible_config.py
    dest: '{{weechat_dir}}/python/autoload/ansible_config.py'
- name: writing config
  copy:
    content: '{{ weechat_settings }}'
    dest: '{{ weechat_dir }}/ansible_weechat.json'
- name: writing config (encrypted)
  copy:
    content: '{{ weechat_settings_encrypted }}'
    dest: '{{ weechat_dir }}/ansible_weechat_encrypted.json'
- name: writing commands
  copy:
    content: '{{ weechat_commands }}'
    dest: '{{ weechat_dir }}/ansible_weechat_commands.json'
- name: writing commands (encrypted)
  copy:
    content: '{{ weechat_commands_encrypted }}'
    dest: '{{ weechat_dir }}/ansible_weechat_commands_encrypted.json'
