- name: installing config plugin
  copy:
    src: files/ansible_config.py
    dest: '{{weechat_dir}}/python/autoload/ansible_config.py'
- name: writing config
  copy:
    content: '{{ weechat_settings }}'
    dest: /tmp/weechat.json
- name: writing config (encrypted)
  copy:
    content: '{{ weechat_settings_encrypted }}'
    dest: /tmp/weechat_encrypted.json
