import weechat as w
import json
import os

import sys
reload(sys)
default_encoding = sys.getdefaultencoding()
sys.setdefaultencoding('utf-8')


def configure(filename):
    w.prnt("", "Loading config from %s" % filename)
    config = {}
    with open(filename) as f:
        config = json.load(f)
    for key in config:
        option = w.config_get(key)
        value = '%s' % config[key]
        w.prnt("", "setting %s to %s" % (key, value))
        w.config_option_set(option, value, 1)
    os.remove(filename)


def run():
    try:
        configure('/tmp/weechat.json')
        configure('/tmp/weechat_encrypted.json')
        w.command('', '/save')
        w.command('', '/upgrade')
    except IOError:
        sys.setdefaultencoding(default_encoding)
        w.hook_signal_send("python_script_remove",
                           w.WEECHAT_HOOK_SIGNAL_STRING, "ansible_config.py")
    return w.WEECHAT_RC_OK


w.register("ansible_config", "irth", "0.1", "MIT",
           "A script to load config generated by ansible", "", "")

run()
